name: Test

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Script to run'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event
        if: false
        run: |
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(job) }}"
          echo "${{ toJSON(steps) }}"
          echo "${{ toJSON(runner) }}"
          echo "${{ toJSON(strategy) }}"
          echo "${{ toJSON(matrix) }}"
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"


      - name: Init Output
        id: init
        run: echo "version=1.2.3" >> $GITHUB_OUTPUT

      - name: Mock Script
        if: false
        id: mock
        run: >
          cat > script.sh <<EOF
            echo "Version: \$VERSION"
            echo "Hello World"
          EOF  

      - name: Run script
        if: false
        env:
          VERSION: ${{ steps.init.outputs.version }}
        run: |
          echo "Running script"
          echo "Output: ${{ toJSON(steps) }}"
          echo "Script: ${{ github.event.inputs.script }}"
          chmod +x "${{ github.event.inputs.script }}" 2>/dev/null || true | bash
          eval "${{ github.event.inputs.script }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "gc_act_test"

      - run: cd gc_act_test

      - name: Run script 2
        uses: ./.github/actions/test
        env:
          VERSION: ${{ steps.init.outputs.version }}
        with:
          script: |
            echo "Version: \$VERSION"
            echo "Hello World"
